#!/bin/bash

echo "+----------------+"
echo "| 42ZEUS (SETUP) |"
echo "+----------------+"

# Don't mess with existing directories :)
if [ -e ~/42zeus ]
then
	echo "Can't clone 42Zeus because the directory ~/42zeus already exists; please rename/remove it first."
	exit
fi

# Clone the tester
echo "Cloning git repository into directory ~/42zeus"
git clone https://github.com/ander-vieira/42zeus.git ~/42zeus

# Build binaries
echo "Building necessary binaries"
make -s -C ~/42zeus

# Add aliases
echo "Adding alias for zeus command"
if [ ! -e ~/.bashrc ] || [ $(cat ~/.bashrc | grep "alias zeus" | wc -l) -eq 0 ]
then
	echo "alias zeus=$HOME/42zeus/zeus" >> ~/.bashrc
	echo "Alias added successfully (bash)"
else
	echo "Alias already exists (bash)"
fi
if [ ! -e ~/.zshrc ] || [ $(cat ~/.zshrc | grep "alias zeus" | wc -l) -eq 0 ]
then
	echo "alias zeus=$HOME/42zeus/zeus" >> ~/.zshrc
	echo "Alias added successfully (zsh)"
else
	echo "Alias already exists (zsh)"
fi

echo "+----------------+"
echo "| SETUP COMPLETE |"
echo "+----------------+"