#!/bin/bash

if [ -t 1 ]
then
	red="\033[0;31m"
	green="\033[0;32m"
	blue="\033[1;36m"
	nocolor="\033[0m"
fi

# Check the testable directory is passed
if [ $# -ge 1 ]
then
	testdir=$1
else
	testdir=.
fi

if [ $testdir == "--update" ]
then
	mv -f ~/42zeus ~/.42zeus_tmp
	curl https://raw.githubusercontent.com/ander-vieira/42zeus/master/setup | bash
	rm -rf ~/.42zeus_tmp
	exit 0
fi

echo -en "${blue}"
echo "+---------------------------------------------------------------------------+";
echo "| █████ █████   ████████     ███████████ ██████████ █████  █████  █████████ |";
echo "|░░███ ░░███   ███░░░░███   ░█░░░░░░███ ░░███░░░░░█░░███  ░░███  ███░░░░░███|";
echo "| ░███  ░███ █░░░    ░███   ░     ███░   ░███  █ ░  ░███   ░███ ░███    ░░░ |";
echo "| ░███████████   ███████         ███     ░██████    ░███   ░███ ░░█████████ |";
echo "| ░░░░░░░███░█  ███░░░░         ███      ░███░░█    ░███   ░███  ░░░░░░░░███|";
echo "|       ░███░  ███      █     ████     █ ░███ ░   █ ░███   ░███  ███    ░███|";
echo "|       █████ ░██████████    ███████████ ██████████ ░░████████  ░░█████████ |";
echo "|      ░░░░░  ░░░░░░░░░░    ░░░░░░░░░░░ ░░░░░░░░░░   ░░░░░░░░    ░░░░░░░░░  |";
echo "+---------------------------------------------------------------------------+";
echo -en "${nocolor}"

echo -e "${green}Version $(cat $(dirname $0)/version.txt)${nocolor}"

if [ ! -d $testdir ]
then
	echo -e "${red}$testdir does not exist or is not a directory${nocolor}"
	exit 1
fi

echo -e "${green}Running on directory $testdir${nocolor}"

# Copy the testable directory into Zeus's local files
cp -R "$testdir" $(dirname $0)/repo/

cd $(dirname $0)

project=$(tools/detectproject)

if [ $project != none ]
then
	echo -e "${green}Detected project $project!${nocolor}"
	$project/tester
	status=$?
	rm -rf repo/
	exit $status
else
	echo -e "${red}Couldn't automatically detect project, stopping...${nocolor}"
	rm -rf repo/
	exit 1
fi