#!/bin/bash

red="\033[0;31m"
green="\033[0;32m"
blue="\033[1;36m"
nocolor="\033[0m"

# Check the testable directory is passed
if [ $# -ne 1 ]
then
	echo "Usage: $(basename $0) <directory>"
	exit 1
fi

echo -en "${blue}"
echo "+------------+"
echo "|   42ZEUS   |"
echo "+------------+"
echo -en "${nocolor}"

if [ ! -d $1 ]
then
	echo -e "${red}$1 does not exist or is not a directory${nocolor}"
	exit 1
fi

echo -e "${green}Running on directory $1${nocolor}"

# Copy the testable directory into Zeus's local files
cp -R $1 $(dirname $0)/repo/

cd $(dirname $0)

project=$(util/detectproject)

if [ $project != none ]
then
	echo -e "${green}Detected project $project!${nocolor}"
	$project/tester
	status=$?
	rm -rf repo/
	exit $status
else
	echo -e "${red}Couldn't automatically detect project, stopping...${nocolor}"
	rm -rf repo/
	exit 1
fi