#!/bin/bash

red="\033[0;31m"
green="\033[0;32m"
blue="\033[1;36m"
nocolor="\033[0m"

echo -en "${blue}"
echo "+---------------------------------------------------------------------------+";
echo "| █████ █████   ████████     ███████████ ██████████ █████  █████  █████████ |";
echo "|░░███ ░░███   ███░░░░███   ░█░░░░░░███ ░░███░░░░░█░░███  ░░███  ███░░░░░███|";
echo "| ░███  ░███ █░░░    ░███   ░     ███░   ░███  █ ░  ░███   ░███ ░███    ░░░ |";
echo "| ░███████████   ███████         ███     ░██████    ░███   ░███ ░░█████████ |";
echo "| ░░░░░░░███░█  ███░░░░         ███      ░███░░█    ░███   ░███  ░░░░░░░░███|";
echo "|       ░███░  ███      █     ████     █ ░███ ░   █ ░███   ░███  ███    ░███|";
echo "|       █████ ░██████████    ███████████ ██████████ ░░████████  ░░█████████ |";
echo "|      ░░░░░  ░░░░░░░░░░    ░░░░░░░░░░░ ░░░░░░░░░░   ░░░░░░░░    ░░░░░░░░░  |";
echo "+---------------------------------------------------------------------------+";
echo -en "${nocolor}"

# Check the testable directory is passed
if [ $# -ne 1 ]
then
	echo "Version $(cat $(dirname $0)/version.txt)"
	echo "Usage: $(basename $0) <directory>"
	exit 1
fi

if [ ! -d $1 ]
then
	echo -e "${red}$1 does not exist or is not a directory${nocolor}"
	exit 1
fi

echo -e "${green}Running on directory $1${nocolor}"

# Copy the testable directory into Zeus's local files
cp -R $1 $(dirname $0)/repo/

cd $(dirname $0)

project=$(tools/detectproject)

if [ $project != none ]
then
	echo -e "${green}Detected project $project!${nocolor}"
	$project/tester
	status=$?
	rm -rf repo/
	exit $status
else
	echo -e "${red}Couldn't automatically detect project, stopping...${nocolor}"
	rm -rf repo/
	exit 1
fi