#!/bin/bash

library=$1
expected_funs=$2
expected_refs=$3

list_funs_1=$(nm $library | grep " T " | awk '{print $3}' | sort -u)
list_refs_1=$(nm $library | grep " U " | awk '{print $2}' | sort -u)

list_funs_2=$(util/bin/filter_list - "$list_funs_1" "$(cat $expected_funs)")

list_refs_2=$(util/bin/filter_list - "$list_refs_1" "$list_funs_1")
list_refs_3=$(util/bin/filter_list - "$list_refs_2" "$(cat $expected_refs)")

echo "Unexpected non-static functions:"
echo "$list_funs_2" | util/indent

echo "Unexpected references to other libraries:"
echo "$list_refs_3"