#!/bin/bash

yellow="\033[0;33m"
green="\033[0;32m"
nocolor="\033[0m"

library=$1
expected_funs=$2
expected_refs=$3

list_funs_1=$(nm $library | grep " T " | awk '{print $3}' | sort -u)
list_refs_1=$(nm $library | grep " U " | awk '{print $2}' | sort -u)

list_funs_2=$(util/bin/filter_list - "$list_funs_1" "$(cat $expected_funs)")

list_refs_2=$(util/bin/filter_list - "$list_refs_1" "$list_funs_1")
list_refs_3=$(util/bin/filter_list - "$list_refs_2" "$(cat $expected_refs)")

if [ $(echo "$list_funs_2" | wc -w) -eq 0 ]
then
	echo -e "${green}All non-static functions OK!${nocolor}"
else
	echo -e "${yellow}Unexpected non-static functions:${nocolor}"
	echo "$list_funs_2"
fi

if [ $(echo "$list_refs_3" | wc -w) -eq 0 ]
then
	echo -e "${green}All references to external functions OK!${nocolor}"
else
	echo -e "${yellow}Possible forbidden functions:${nocolor}"
	echo "$list_refs_3"
fi