#!/bin/bash

if [ -t 1 ]
then
	red="\033[0;31m"
	green="\033[0;32m"
	blue="\033[1;36m"
	nocolor="\033[0m"
fi

status=0

echo -en "${blue}"
echo "+-----------+"
echo "|   libft   |"
echo "+-----------+"
echo -en "${nocolor}"

echo "+----------------+"
echo "|   NORMINETTE   |"
echo "+----------------+"

tools/normcheck repo/
if [ $? -ne 0 ]
then
	status=1
fi

echo -en "${blue}"
echo "+---------------------------+"
echo "|   libft: MANDATORY PART   |"
echo "+---------------------------+"
echo -en "${nocolor}"

echo "+---------------------+"
echo "|   COMPILE LIBRARY   |"
echo "+---------------------+"

make -s -C repo/ all clean
if [ $? -ne 0 ]
then
	echo -e "${red}Errors while compiling the library${nocolor}"
	make -s -C repo/ fclean
	exit 1
else
	echo -e "${green}Library compiled successfully!${nocolor}"
fi

echo "+---------------------+"
echo "|   CHECK SYMBOLS     |"
echo "+---------------------+"

tools/symbolcheck repo/libft.a libft/symbols/functions libft/symbols/externals

echo "+-------------------+"
echo "|   COMPILE TESTS   |"
echo "+-------------------+"

make -s  -C libft/ all clean
if [ $? -ne 0 ]
then
	echo -e "${red}Errors while compiling tests${nocolor}"
	make -s -C libft/ fclean
	exit 1
else
	echo -e "${green}Tests compiled successfully!${nocolor}"
fi

echo "+-----------+"
echo "|   TESTS   |"
echo "+-----------+"

libft/test.out
if [ $? -ne 0 ]
then
	status=1
fi

make -s -C libft/ fclean

if [ $(tools/bonuscheck) == yes ]
then
	echo -en "${blue}"
	echo "+-----------------------+"
	echo "|   libft: BONUS PART   |"
	echo "+-----------------------+"
	echo -en "${nocolor}"

	echo "+-----------------------------+"
	echo "|   COMPILE LIBRARY (BONUS)   |"
	echo "+-----------------------------+"

	make -s -C repo/ bonus clean
	if [ $? -ne 0 ]
	then
		echo -e "${red}Errors while compiling the library${nocolor}"
		make -s -C repo/ fclean
		exit 1
	else
		echo -e "${green}Library compiled successfully!${nocolor}"
	fi

	echo "+-----------------------------+"
	echo "|   CHECK SYMBOLS (BONUS)     |"
	echo "+-----------------------------+"

	tools/symbolcheck repo/libft.a libft/symbols/functions_bonus libft/symbols/externals

	echo "+---------------------------+"
	echo "|   COMPILE TESTS (BONUS)   |"
	echo "+---------------------------+"

	make -s  -C libft/ bonus clean
	if [ $? -ne 0 ]
	then
		echo -e "${red}Errors while compiling tests${nocolor}"
		make -s -C libft/ fclean
		exit 1
	else
		echo -e "${green}Tests compiled successfully!${nocolor}"
	fi

	echo "+-------------------+"
	echo "|   TESTS (BONUS)   |"
	echo "+-------------------+"

	libft/test_bonus.out
	if [ $? -ne 0 ]
	then
		status=1
	fi

	make -s -C libft/ fclean
else
	echo -e "${green}Bonus part not found!${nocolor}"
fi
