#!/bin/bash

util/bin/print_title "libft: Mandatory part"

echo "Building project..."
make -s -C repo/ all clean

echo "Checking symbols..."
util/check_symbols repo/libft.a libft/expected_funs libft/expected_refs | util/indent

if [ $(util/detect_bonus) == yes ]
then
	util/bin/print_title "libft: Bonus part"

	echo "Building bonus..."
	make -s -C repo/ bonus clean

	echo "Checking bonus symbols..."
	util/check_symbols repo/libft.a libft/expected_funs_bonus libft/expected_refs | util/indent
else
	echo "Project doesn't have bonus rule"
fi
