# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: andeviei <andeviei@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/19 01:09:18 by andeviei          #+#    #+#              #
#    Updated: 2023/12/19 01:10:07 by andeviei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: filterlist.out

filterlist.out: src/filterlist.c
	gcc src/filterlist.c -o filterlist.out

.PHONY: all