#!/bin/bash

if [ -t 1 ]
then
	red="\033[0;31m"
	green="\033[0;32m"
	nocolor="\033[0m"
fi

if [ $# -lt 1 ]
then
	echo -e "${red}No filename specified.${nocolor}"
	exit 1
fi

norminette=$(norminette $1 | grep -v ': OK!$')
if [ $? -ne 0 ]
then
	echo -e "${green}No norminette errors!${nocolor}"
	exit 0
else
	echo -e "${red}${norminette}${nocolor}"
	exit 1
fi