#!/bin/bash

yellow="\033[0;33m"
green="\033[0;32m"
nocolor="\033[0m"

library=$1
expected_funs=$2
expected_refs=$3

symbols=$(nm --demangle $library)

list_funs_1=$(echo -n "$symbols" | grep " T " | awk '{print $3}' | sed 's/^_*//g' | sort -u)
list_refs_1=$(echo -n "$symbols" | grep " U " | awk '{print $2}' | sed 's/^_*//g' | sort -u)
list_globals_1=$(echo -n "$symbols" | grep -e " C " -e " D " | awk '{print $3}' | sort -u)

list_funs_2=$(tools/filterlist.out - "$(cat $expected_funs)" "$list_funs_1" )

list_refs_2=$(tools/filterlist.out - "$list_refs_1" "$list_funs_1")
list_refs_3=$(tools/filterlist.out - "$list_refs_2" "$(cat $expected_refs)")

if [ $(echo "$list_funs_2" | wc -w) -eq 0 ]
then
	echo -e "${green}All required functions found!${nocolor}"
else
	echo -e "${yellow}Missing functions:"
	echo "$list_funs_2"
	echo -e "${nocolor}"
fi

if [ $(echo "$list_refs_3" | wc -w) -eq 0 ]
then
	echo -e "${green}No forbidden functions!${nocolor}"
else
	echo -e "${yellow}Possible forbidden functions:"
	echo "$list_refs_3"
	echo -e "${nocolor}"
fi

if [ $(echo "$list_globals_1" | wc -w) -eq 0 ]
then
	echo -e "${green}No global variables!${nocolor}"
else
	echo -e "${yellow}Global variables used:"
	echo "$list_globals_1"
	echo -e "${nocolor}"
fi